// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TRANSPORTES.WEB.Context;

#nullable disable

namespace TRANSPORTES.WEB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230322033100_MigracaoInicialTransportes")]
    partial class MigracaoInicialTransportes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TRANSPORTES.REPOSITORY.Models.Entidades.EntidadeCliente", b =>
                {
                    b.Property<decimal>("ClienteId")
                        .HasColumnType("decimal(13,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClienteId");

                    b.ToTable("EntidadeClientes");
                });

            modelBuilder.Entity("TRANSPORTES.WEB.Models.Entidades.Conteiner", b =>
                {
                    b.Property<decimal>("ConteinerId")
                        .HasColumnType("decimal(13,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("ClienteId")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("EntidadeClienteClienteId")
                        .HasColumnType("decimal(13,2)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Tipo")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("ConteinerId");

                    b.HasIndex("EntidadeClienteClienteId");

                    b.ToTable("Conteiners");
                });

            modelBuilder.Entity("TRANSPORTES.WEB.Models.Entidades.Movimentacao", b =>
                {
                    b.Property<decimal>("MovimentacaoId")
                        .HasColumnType("decimal(13,2)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("ConteinerId")
                        .HasColumnType("decimal(13,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("MovimentacaoId");

                    b.HasIndex("ConteinerId");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("TRANSPORTES.WEB.Models.Entidades.Conteiner", b =>
                {
                    b.HasOne("TRANSPORTES.REPOSITORY.Models.Entidades.EntidadeCliente", "EntidadeCliente")
                        .WithMany("Conteiners")
                        .HasForeignKey("EntidadeClienteClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntidadeCliente");
                });

            modelBuilder.Entity("TRANSPORTES.WEB.Models.Entidades.Movimentacao", b =>
                {
                    b.HasOne("TRANSPORTES.WEB.Models.Entidades.Conteiner", "Conteiner")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ConteinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conteiner");
                });

            modelBuilder.Entity("TRANSPORTES.REPOSITORY.Models.Entidades.EntidadeCliente", b =>
                {
                    b.Navigation("Conteiners");
                });

            modelBuilder.Entity("TRANSPORTES.WEB.Models.Entidades.Conteiner", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
